services:
  dev-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
  redis:
    image: redis:7
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    environment:
      REDIS_HOSTS: local:redis:6379

volumes:
  postgres-data:
